#!/bin/bash
# ============================================================
#  Phase 6: Install GRUB Bootloader (UEFI)
# ============================================================

set -euo pipefail

LFS=${LFS:-/mnt/lfs}
LFS_DISK=${LFS_DISK:-/dev/sdb}
JOBS=${LFS_JOBS:-$(nproc)}
KERNEL_VERSION="6.6.30"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${CYAN}[grub]${NC} $*"; }
ok()   { echo -e "${GREEN}  ✔ $*${NC}"; }
err()  { echo -e "${RED}  ✘ $*${NC}"; exit 1; }

[[ "$EUID" -eq 0 ]] || err "Must run as root"

# ── Mount EFI ────────────────────────────────────────────────
log "Ensuring EFI partition is mounted..."
if [[ "$LFS_DISK" == *"nvme"* ]] || [[ "$LFS_DISK" == *"mmcblk"* ]]; then
  EFI_PART="${LFS_DISK}p1"
else
  EFI_PART="${LFS_DISK}1"
fi

mkdir -pv "$LFS/boot/efi"
mountpoint -q "$LFS/boot/efi" || mount "$EFI_PART" "$LFS/boot/efi"

# Mount virtual fs for chroot
mount --bind /dev  "$LFS/dev"
mount -t proc proc "$LFS/proc"
mount -t sysfs sys "$LFS/sys"
mount -t efivarfs efivarfs /sys/firmware/efi/efivars 2>/dev/null || \
  log "efivarfs not available (non-EFI host — GRUB will be BIOS)"

# ── Build GRUB inside chroot ─────────────────────────────────
log "Building and installing GRUB..."

chroot "$LFS" /usr/bin/env -i \
  HOME=/root TERM="$TERM" PATH=/usr/bin:/usr/sbin \
  JOBS="$JOBS" KERNEL_VERSION="$KERNEL_VERSION" \
  /bin/bash << 'CHROOT'

set -euo pipefail
SOURCES=/sources
JOBS=${JOBS:-$(nproc)}

echo "── Building GRUB ──"
archive=$(ls "$SOURCES"/grub-*.tar.xz 2>/dev/null | head -1)
[ -z "$archive" ] && { echo "  ✘ grub source not found"; exit 1; }

mkdir -p /tmp/grub-build
tar -xf "$archive" -C /tmp/grub-build
cd /tmp/grub-build/grub-*/

./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --disable-efiemu \
  --enable-grub-mkfont \
  --with-platform=efi \
  --target=x86_64 \
  --disable-werror

make -j"$JOBS"
make install
mv -v /etc/grub.d/50_osprober /etc/grub.d/50_osprober.bak

# Install to EFI
grub-install --target=x86_64-efi \
  --efi-directory=/boot/efi \
  --bootloader-id=LFS \
  --recheck \
  --no-floppy

echo "  ✔ GRUB EFI installed"

# ── Generate grub.cfg ─────────────────────────────────────────
ROOT_UUID=$(blkid -s UUID -o value "$(findmnt -n -o SOURCE /)" 2>/dev/null || echo "CHANGEME")
KERNEL_VERSION=${KERNEL_VERSION:-6.6.30}
VMLINUZ=$(ls /boot/vmlinuz-* 2>/dev/null | head -1 | xargs basename)
INITRD=$(ls /boot/initramfs-* 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "")

cat > /boot/grub/grub.cfg << GRUBCFG
# ── LFS GRUB Configuration ──────────────────────────────────
# Generated by lfs-distro build system

set default=0
set timeout=5
set timeout_style=menu

# Theme
if [ -f /boot/grub/themes/lfs/theme.txt ]; then
  set theme=/boot/grub/themes/lfs/theme.txt
fi

insmod part_gpt
insmod ext2
insmod all_video
insmod font

# ── LFS Entry ─────────────────────────────────────────────
menuentry "Linux From Scratch ${KERNEL_VERSION}-lfs" {
  set root='hd0,gpt3'
  search --no-floppy --fs-uuid --set=root $ROOT_UUID
  linux   /boot/$VMLINUZ root=UUID=$ROOT_UUID rw quiet loglevel=3
  $([ -n "$INITRD" ] && echo "initrd  /boot/$INITRD")
}

menuentry "LFS — verbose boot (no quiet)" {
  set root='hd0,gpt3'
  search --no-floppy --fs-uuid --set=root $ROOT_UUID
  linux   /boot/$VMLINUZ root=UUID=$ROOT_UUID rw
  $([ -n "$INITRD" ] && echo "initrd  /boot/$INITRD")
}

menuentry "LFS — recovery (single user)" {
  set root='hd0,gpt3'
  search --no-floppy --fs-uuid --set=root $ROOT_UUID
  linux   /boot/$VMLINUZ root=UUID=$ROOT_UUID rw single
}
GRUBCFG

echo "  ✔ grub.cfg written"
cat /boot/grub/grub.cfg

# Cleanup
rm -rf /tmp/grub-build
CHROOT

ok "GRUB installation complete"

# ── Unmount ───────────────────────────────────────────────────
umount "$LFS/dev"
umount "$LFS/proc"
umount "$LFS/sys"
umount /sys/firmware/efi/efivars 2>/dev/null || true

log "Boot files in $LFS/boot:"
ls -lh "$LFS/boot/"
ok "System is bootable! Remove installation media and reboot."
