#!/bin/bash
# ============================================================
#  Phase 1: Disk Partitioning & Filesystem Creation
#  Layout:
#    /dev/sdX1  →  512MB   EFI System Partition (FAT32)
#    /dev/sdX2  →  2GB     swap
#    /dev/sdX3  →  rest    root ext4
# ============================================================

set -euo pipefail

LFS=${LFS:-/mnt/lfs}
LFS_DISK=${LFS_DISK:-/dev/sdb}

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${CYAN}[partition]${NC} $*"; }
ok()   { echo -e "${GREEN}  ✔ $*${NC}"; }
err()  { echo -e "${RED}  ✘ $*${NC}"; exit 1; }
warn() { echo -e "${YELLOW}  ⚠ $*${NC}"; }

# Safety check
[[ "$EUID" -ne 0 ]] && err "Must run as root"
[[ ! -b "$LFS_DISK" ]] && err "Disk $LFS_DISK not found. Set LFS_DISK env var."

log "Target disk: ${BOLD}$LFS_DISK${NC}"
echo ""
lsblk "$LFS_DISK" 2>/dev/null || true
echo ""
warn "ALL DATA ON $LFS_DISK WILL BE DESTROYED!"
read -rp "  Type 'yes' to continue: " CONFIRM
[[ "$CONFIRM" != "yes" ]] && { log "Aborted."; exit 0; }

# ── Partition ────────────────────────────────────────────────
log "Creating GPT partition table on $LFS_DISK..."
parted -s "$LFS_DISK" mklabel gpt

log "Creating EFI partition (512MB)..."
parted -s "$LFS_DISK" mkpart ESP fat32 1MiB 513MiB
parted -s "$LFS_DISK" set 1 esp on

log "Creating swap partition (2GB)..."
parted -s "$LFS_DISK" mkpart primary linux-swap 513MiB 2561MiB

log "Creating root partition (remaining space)..."
parted -s "$LFS_DISK" mkpart primary ext4 2561MiB 100%

# ── Detect partition names ────────────────────────────────────
# Handles both /dev/sdb1 and /dev/nvme0n1p1 naming
if [[ "$LFS_DISK" == *"nvme"* ]] || [[ "$LFS_DISK" == *"mmcblk"* ]]; then
  EFI_PART="${LFS_DISK}p1"
  SWAP_PART="${LFS_DISK}p2"
  ROOT_PART="${LFS_DISK}p3"
else
  EFI_PART="${LFS_DISK}1"
  SWAP_PART="${LFS_DISK}2"
  ROOT_PART="${LFS_DISK}3"
fi

# ── Format ───────────────────────────────────────────────────
log "Formatting EFI partition as FAT32..."
mkfs.fat -F32 -n "LFS-EFI" "$EFI_PART"
ok "EFI: $EFI_PART"

log "Creating swap..."
mkswap -L "LFS-SWAP" "$SWAP_PART"
ok "Swap: $SWAP_PART"

log "Formatting root as ext4..."
mkfs.ext4 -L "LFS-ROOT" -O "^64bit" "$ROOT_PART"
ok "Root: $ROOT_PART"

# ── Mount ────────────────────────────────────────────────────
log "Mounting filesystems..."
mkdir -pv "$LFS"
mount -v "$ROOT_PART" "$LFS"

mkdir -pv "$LFS/boot/efi"
mount -v "$EFI_PART" "$LFS/boot/efi"

swapon -v "$SWAP_PART"

# ── Verify ───────────────────────────────────────────────────
echo ""
log "Mount status:"
df -hT "$LFS" "$LFS/boot/efi"
echo ""
ok "Partitioning complete!"
echo ""
echo "  EFI  : $EFI_PART  →  $LFS/boot/efi"
echo "  Swap : $SWAP_PART"
echo "  Root : $ROOT_PART  →  $LFS"

# ── fstab snippet ────────────────────────────────────────────
ROOT_UUID=$(blkid -s UUID -o value "$ROOT_PART")
EFI_UUID=$(blkid -s UUID -o value "$EFI_PART")
SWAP_UUID=$(blkid -s UUID -o value "$SWAP_PART")

cat > /tmp/lfs-fstab-snippet << FSTAB
# LFS /etc/fstab — generated by partition.sh
UUID=$ROOT_UUID  /           ext4   defaults,noatime  0 1
UUID=$EFI_UUID   /boot/efi   vfat   defaults          0 2
UUID=$SWAP_UUID  none        swap   sw                0 0
tmpfs            /tmp        tmpfs  defaults,size=512M 0 0
FSTAB

log "fstab snippet saved to /tmp/lfs-fstab-snippet"
cat /tmp/lfs-fstab-snippet
